apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mainnet-replica-l1-0-5-11
commonLabels:
  network: mainnet
  provider: internal

bases:
  - ../../envs/mainnet-gen5-l1/

resources:
  - ../../bases/data-transport-layer
  - ../../bases/l2geth-replica
  - ../../bases/configmaps
  - ../../bases/servicemonitors
  - ../../bases/replica-healthcheck
  - ./l2geth-volume.yaml

images:
  - name: ethereumoptimism/data-transport-layer
    newName: ethereumoptimism/data-transport-layer@sha256
    newTag: fe7e84c27e31121af09bcfb485ee11f4ba27d6113f3aee2dd244f07200331e2e
  - name: ethereumoptimism/l2geth
    newName: ethereumoptimism/l2geth
    newTag: 0.5.11
  - name: ethereumoptimism/replica-healthcheck
    newName: ethereumoptimism/replica-healthcheck
    newTag: 0.3.6

patchesStrategicMerge:
  - ./patches/l2geth-resources.yaml
  - ./patches/replica-healthcheck.yaml

patches:
  - path: ./patches/l2geth-volume.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: l2geth-replica