---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2geth-replica-data
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
