apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-healthcheck
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: replica-healthcheck
          env:
            - name: REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER
              value: http://sequencer.default:8545
